import Head from "next/head";
import React from "react";
import NavHeader from "@/components/header/NavHeader";
import Image from "next/image";
import FooterNav from "../footer/FooterNav";
import { useRouter } from "next/router";
import cityBg from "../../../public/assets/images/city-bg.png";
import topography from "../../../public/assets/images/map-layout.png";

interface Layout {
  children: React.ReactNode;
  title?: string;
}

const PageLayouts = (props: Layout) => {
  const { title, children } = props;
  const { pathname } = useRouter();
  return (
    <>
      <Head>
        <title>{`Diskominfo Kota Serang ${
          pathname === "/" ? "" : `| ${title}`
        }`}</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <main>
        <NavHeader />
        <div className="relative h-full overflow-hidden">
          <div className="container indent-5 mx-auto min-h-screen pt-10 font-serif z-40">
            {children}
          </div>
          <Image
            src={topography}
            alt="Background Image for Webpage"
            className="object-cover w-full absolute mix-blend-multiply top-0 -z-[9]"
          />
          <Image
            src={cityBg}
            alt="Background Image for Webpage"
            className="object-cover w-full absolute bottom-0 -z-10"
          />
        </div>
        <FooterNav />
      </main>
    </>
  );
};

export default PageLayouts;
